src/components/titre/administration.vue, src/components/titre/repertoire.vue
https://trello.com/c/6nKp8S8j/50-feat-api-connexion-api-annuaire-admin
https://github.com/MTES-MCT/camino-api/pull/23
=> feat(titre): ajout des administrations

src/components/content/cgu-1-0-0.vue, src/components/content/cgu-v1-0.vue, src/components/content/cgu.vue, src/router/index.js
Mise à jour de la page CGU avec la v.2.0
Ajout du lien vers la version v.1.0 des CGU
Ajout de la page  pour la v.1.0 des CGU 
Mise à jour de la page mentions légales
=> Mise à jour CGU & mentions légales

src/components/titres.vue, src/components/titres/csv-download.vue, src/components/titres/geojson-download.vue
@francoisromain problème avec le mobile qui n'affiche pas les 2 boutons de téléchargement ainsi que le bouton de switch entre vue-liste et vu-map.
=> feat: télécharge un geojson des titres

src/components/titres/csv-download.vue, src/components/titres/geojson-download.vue
feat: ajoute une redirection de stats vers statistiques
fix(csv): corrige le format de la date dans le nom du fichier
=> fix(csv/geojson): corrige le nom de fichier

src/components/_ui/filters-input.vue
- identifie le filtre et le passe dans le onBlur
- ajout d'une prop `inputNotChanged` contenant tous les filtres concernés (au cas ou il y en ai d'autres dans le futur)
- passe l'id du filtre concerné dans la méthode `inputChange` et prend en compte le tiret pour ce cas.
=> fix(filtres): considérer les tirets dans le filtre références

src/api/fragments/activite.js, src/api/fragments/entreprise.js, src/api/fragments/etape.js, src/api/fragments/utilisateur.js, src/components/activite/detail.vue, src/components/entreprise.vue, src/components/menu/menu.vue, src/components/titre/document/button-add.vue, src/components/titre/document/edit.vue, src/components/titre/document/tr.vue, src/components/titres/table.vue, src/components/utilisateur.vue, src/components/utilisateur/edit-popup.vue
https://github.com/MTES-MCT/camino-api/pull/270
=> feat: supprime des vérifications de permissions du front

src/api/titres-demarches.js, src/components/demarches/filtres.js, src/store/titres-demarches.js
…bstances,références,territoires
=> feat(démarches): filtre les démarches par nom de titres,titulaires,substances,références,territoires

src/components/demarches/table.js
https://github.com/MTES-MCT/camino-api/pull/392
=> fix: corrige le tri des démarches

src/components/titres/map.js, src/css/system/typography.css, src/css/system/ui.css
Le filter drop-shadow fait souffrir mon navigateur sur les animations.
Je trouvais dommage de faire un text-transform CSS (coûteux) alors qu'il est possible de l'avoir dès le début.
=> Performance

src/router/index.js
https://router.vuejs.org/guide/advanced/lazy-loading.html#grouping-components-in-the-same-chunk
=> perf(stats): charge la page des statistiques de façon asynchrone

docker-compose.localhost.yml, index.js, package-lock.json, package.json, src/api/_client.js, src/api/_client.test.js, src/store/index.js, src/store/index.test.js
docker-compose -f docker-compose.localhost.yml up -d
=> build(docker): enlève le middleware pour accéder à l’API

src/components/titre/etape/edit-fondamentales.vue
=> fix(entreprise): ne permet pas de choisir une entreprise amodiataire si elle est titulaire

readme.md, src/components/activite/edit-popup.vue, src/components/content/about.vue, src/components/content/cgu-1-0-0.vue, src/components/content/cgu.vue, src/components/content/contacts.vue, src/components/content/mentions-legales.vue, src/components/page/footer.vue, src/router/index.js
=> feat: met à jour le nom du ministère et les coordonnées

src/components/titre.vue
Dans le cas où l'unique rapport est supprimé : l'onglet courant devient 'Droits miniers'
=> fix(rapport): corrige l'onglet courant ('Droits miniers' par défaut)

src/api/fragments/metas-activites.js, src/components/_ui/popup.vue, src/components/activite/detail.vue, src/components/activite/edit-popup.vue, src/components/activite/remove-popup.vue, src/components/administration/edit-popup.vue, src/components/document/edit-popup.vue, src/components/document/remove-popup.vue, src/components/entreprise/add-popup.vue, src/components/entreprise/edit-popup.vue, src/components/justificatifs/edit-popup.vue, src/components/justificatifs/unlink-popup.vue, src/components/titre/demarche-edit-popup.vue, src/components/titre/demarche-remove-popup.vue, src/components/titre/edit-popup.vue, src/components/titre/etape/edit.vue, src/components/titre/etape/remove.vue, src/components/titre/remove-popup.vue, src/components/titre/travau-etape/edit.vue, src/components/titre/travau-etape/remove.vue, src/components/titre/travaux-edit-popup.vue, src/components/titre/travaux-remove-popup.vue, src/components/user/add-popup.vue, src/components/user/login-popup.vue, src/components/user/password-init-popup.vue, src/components/utilisateur/edit-popup.vue, src/components/utilisateur/email-popup.vue, src/components/utilisateur/password-popup.vue, src/components/utilisateur/remove-popup.vue, src/store/metas-definitions.js
affiche les descriptions dans les rapports, et dans l'administration des types d'activité
=> feat(activites): ajoute des descriptions pour les types d'activité

src/api/fragments/metas.js, src/api/titres-travaux.js, src/components/titre/travaux-edit-popup.vue, src/store/document.js, src/store/metas-definitions.js, src/store/titre-travaux.js
Co-authored-by: vmaubert <vmaubert@users.noreply.github.com>
=> fix(documents): supprime la colonne répertoire

src/api/fragments/entreprises.js, src/api/fragments/metas.js, src/api/fragments/titre-etape.js, src/api/titres-etapes.js, src/components/etape-edit.vue, src/components/etape/edit-justificatifs.vue, src/store/__mocks__/titre-etape.js, src/utils/titre-etape-edit.js, src/utils/titre-etape-edit.test.js, src/utils/titre-etape-heritage-build.js, src/utils/titre-etape-save.js, src/utils/titre-etape-save.test.js
=> feat(justificatifs): ajoute un bloc permettant de lier les justificatifs dans une étape

.husky/pre-commit, .husky/pre-push, package-lock.json, package.json
Linting pré-commit, lancement de tests pré-push.
=> chore(git): ajout de husky

src/components/_common/filtres.vue, src/components/entreprises.vue, src/components/journaux/journaux.vue, src/components/metas.vue
=> Fix liste filtres

package-lock.json, package.json
=> build(react): supprime les dépendances à React dans le projet

jest.config.js, src/components/etape/edit.vue, src/components/etape/fondamentales-edit.test.ts, src/components/etape/fondamentales-edit.vue
https://trello.com/c/ytG8LdNU/93-featpropri%C3%A9t%C3%A9s-masquer-les-champs-date-de-d%C3%A9but-et-date-d%C3%A9ch%C3%A9ance-pour-les-profils-admin
=> feat(proprietes): masque l'affichage des dates début/fin pour admin

src/api/geojson.js, src/api/titres-etapes.js, src/components/etape/edit.vue, src/store/titre-etape-edition.js
=> feat(sdom): vérifie les documents obligatoires en fonction des zones du SDOM
